# Generated by Django 3.1.4 on 2021-01-02 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonsocial', models.CharField(max_length=50, verbose_name='Razon social')),
                ('rfc', models.CharField(max_length=16, unique=True)),
                ('tfno', models.CharField(max_length=10, verbose_name='Telefono')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=50)),
                ('tfno', models.CharField(max_length=10, verbose_name='Telefono')),
                ('activo', models.BooleanField(default=True)),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('folio_in', models.IntegerField()),
                ('folio_fin', models.IntegerField()),
                ('area', models.CharField(max_length=20)),
                ('no_personas', models.IntegerField()),
                ('capturado_por', models.CharField(max_length=20)),
                ('monto_tarjeta', models.FloatField()),
                ('monto_efectivo', models.FloatField()),
                ('monto_cortesia', models.FloatField()),
                ('monto_ta_express', models.FloatField()),
                ('monto_apps', models.FloatField()),
                ('importe', models.FloatField()),
                ('iva', models.FloatField()),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OtatesApp.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('folio', models.IntegerField()),
                ('t_movimiento', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('no_items', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('importe', models.FloatField()),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
                ('nn_rr', models.CharField(max_length=2, verbose_name='RR NN')),
                ('capturado_por', models.CharField(max_length=20)),
                ('autorizado_por', models.CharField(max_length=20)),
                ('observaciones', models.CharField(max_length=20)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OtatesApp.proveedor')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OtatesApp.sucursal')),
            ],
        ),
    ]
