# Generated by Django 3.1.4 on 2021-01-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtatesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='responsable',
            field=models.CharField(max_length=20, verbose_name='Responsable'),
        ),
    ]
