# Generated by Django 3.1.4 on 2021-01-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtatesApp', '0002_auto_20210102_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='proveedor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='sucursal',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='sucursal',
            field=models.CharField(max_length=30),
        ),
    ]
