# Generated by Django 3.1.4 on 2021-01-04 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OtatesApp', '0005_auto_20210104_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Empleado',
        ),
    ]
