# Generated by Django 3.1.4 on 2021-01-07 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OtatesApp', '0008_auto_20210104_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtatesApp.sucursal'),
        ),
    ]
