# Generated by Django 3.1.4 on 2021-01-07 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OtatesApp', '0009_auto_20210106_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='autorizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='nn_rr',
            field=models.CharField(choices=[(1, 'NN'), (2, 'RR')], max_length=2),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtatesApp.proveedor'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtatesApp.sucursal'),
        ),
    ]
