# Generated by Django 3.1.4 on 2021-01-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtatesApp', '0010_auto_20210106_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='nn_rr',
            field=models.CharField(choices=[(1, 'NN'), (2, 'RR')], max_length=2, verbose_name='NN-RR'),
        ),
    ]
