# Generated by Django 3.1.4 on 2021-01-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtatesApp', '0012_auto_20210108_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
