# Generated by Django 3.1.4 on 2021-01-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtatesApp', '0013_auto_20210108_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='nn_rr',
            field=models.CharField(choices=[('NN', 'NN'), ('RR', 'RR')], max_length=2, verbose_name='NN-RR'),
        ),
    ]
